backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

locale: 'fr'

collections:
  - name: "blog"
    label: "Articles de blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image principale", name: "image", widget: "image", required: false }
      - { label: "Description (SEO)", name: "description", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      
